// Generated from the actual backend OpenAPI. Run pnpm generate:api after contract changes.
export interface Schemas {
  "ActionData": { "assigned_to": string | null; "case_id": string | null; "created_at": number; "document_id": string; "due_at": number | null; "id": string; "kind": string; "outcome": Record<string, unknown> | null; "period": string; "registration_id": string; "reminded_at": number | null; "result_id": string; "run_id": string; "source": Record<string, unknown>; "sources_current": boolean; "state": "OPEN" | "AWAITING_SUPPLIER" | "EVIDENCE_REQUIRED" | "REVIEW_REQUIRED" | "CLOSED"; "timeline": Array<Record<string, unknown>>; "updated_at": number; "version": number; "workspace_id": string; };
  "ActionListData": { "actions": Array<Schemas["ActionData"]>; "automation": Schemas["AutomationData"]; "next_cursor": string | null; };
  "ActionListResponse": { "data": Schemas["ActionListData"]; "meta": Schemas["Meta"]; };
  "ActionOutcome": { "amount"?: string | null; "decision"?: "REVIEW_ACCEPTED" | "EVIDENCE_REQUIRED" | "REJECTED" | null; "evidence_event_ids"?: Array<string>; "expected_version": number; "kind": "REVIEW_DECISION" | "FILING_OBSERVATION" | "NOTICE_SUBMISSION_OBSERVATION"; "observed_on"?: string | null; "provenance"?: "USER_PROVIDED" | "SYNTHETIC_DEMO"; "reason": string; "reference"?: string | null; };
  "ActionResponse": { "data": Schemas["ActionData"]; "meta": Schemas["Meta"]; };
  "ActionUpdate": { "assigned_to"?: string | null; "expected_version": number; "reason": string; "review_on"?: string | null; "state": "OPEN" | "AWAITING_SUPPLIER" | "EVIDENCE_REQUIRED" | "REVIEW_REQUIRED" | "CLOSED"; };
  "Allocation": { "amount": string; "document_id": string; "purpose": "SUPPLIER_PROPOSED" | "INTERNAL_RESERVE_ILLUSTRATIVE"; };
  "ArtifactCreate": { "expected_version": number; "kind": "RECONCILIATION_PDF" | "EVIDENCE_PDF" | "PROPOSAL_CSV" | "ROW_ERRORS_CSV"; "selected_result_ids"?: Array<string>; "source_id": string; };
  "ArtifactData": { "created_at": number; "error_code": string | null; "expires_at": number; "filename": string; "id": string; "job_id": string; "kind": "RECONCILIATION_PDF" | "EVIDENCE_PDF" | "PROPOSAL_CSV" | "ROW_ERRORS_CSV"; "manifest": Record<string, unknown>; "mime_type": string; "provenance": "USER_PROVIDED" | "SYNTHETIC_DEMO"; "sha256": string | null; "size_bytes": number | null; "snapshot_sha256": string; "source_id": string; "source_version": number; "sources_current": boolean; "state": "PENDING" | "READY" | "FAILED" | "EXPIRED"; "updated_at": number; "workspace_id": string; };
  "ArtifactResponse": { "data": Schemas["ArtifactData"]; "meta": Schemas["Meta"]; };
  "AutomationData": { "channel_delivery"?: "NOT_IMPLEMENTED"; "checked_at": number | null; "error_code": string | null; "interval_seconds": number; "pending_sources": number; };
  "BalanceObservation": { "document_id": string; "evidence_case_id": string; "expected_case_version": number; };
  "CandidateData": { "amount_differences": Record<string, string | null>; "currently_available": boolean; "hard_gates_passed": boolean; "id": string; "invoice_date": string; "original_invoice_number": string; "portal_document_id": string; "rank": number; "reason_codes": Array<string>; "score": string; };
  "CaseCreate": { "amount": string; "currency"?: "INR"; "facts"?: Record<string, unknown>; "kind": "MSME_REVIEW" | "RULE37_REVIEW" | "RULE37A_REVIEW" | "IRN_REVIEW" | "NOTICE_REVIEW"; "purchase_document_id": string; "registration_id": string; "result_id": string; };
  "CaseData": { "amount": string; "created_at": number; "currency": "INR"; "facts": Record<string, unknown>; "id": string; "irn_observation": "NOT_PROVIDED" | "FORMAT_ONLY" | "FORMAT_INVALID"; "kind": "MSME_REVIEW" | "RULE37_REVIEW" | "RULE37A_REVIEW" | "IRN_REVIEW" | "NOTICE_REVIEW"; "missing_facts": Array<string>; "provenance": "USER_PROVIDED" | "SYNTHETIC_DEMO"; "purchase_document_id": string; "registration_id": string; "result_id": string; "state": "OPEN" | "EVIDENCE_REQUIRED" | "REVIEW_READY" | "CLOSED"; "timeline": Array<Record<string, unknown>>; "updated_at": number; "version": number; "workspace_id": string; };
  "CaseEvidence": { "event_kind": "NOTE" | "DOCUMENT" | "PAYMENT_OBSERVATION" | "FILING_OBSERVATION" | "ACCEPTANCE_OBSERVATION" | "IRN_OBSERVATION"; "expected_version": number; "facts_patch"?: Record<string, unknown>; "import_id"?: string | null; "reason": string; };
  "CaseListData": { "cases": Array<Schemas["CaseData"]>; "next_cursor": string | null; };
  "CaseListResponse": { "data": Schemas["CaseListData"]; "meta": Schemas["Meta"]; };
  "CaseResponse": { "data": Schemas["CaseData"]; "meta": Schemas["Meta"]; };
  "CaseTransition": { "expected_version": number; "reason": string; "state": "OPEN" | "EVIDENCE_REQUIRED" | "REVIEW_READY" | "CLOSED"; };
  "CleanupCreate": { "expired_only"?: true; };
  "CleanupData": { "expired_artifacts": number; "scope": "EXPIRED_ARTIFACT_CONTENT_ONLY"; };
  "CleanupResponse": { "data": Schemas["CleanupData"]; "meta": Schemas["Meta"]; };
  "ErrorBody": { "code": string; "details": Array<Schemas["ErrorDetail"]>; "message": string; "retryable": boolean; };
  "ErrorDetail": { "field": string; "reason": string; "row"?: number | null; };
  "ErrorResponse": { "error": Schemas["ErrorBody"]; "meta": Schemas["Meta"]; };
  "Followup": { "contact": string; "draft_id"?: string | null; "expected_version": number; "kind"?: "DRAFT" | "ATTEMPT_RECORDED"; "observed_on"?: string | null; "reason": string; "request": string; };
  "HTTPValidationError": { "detail"?: Array<Schemas["ValidationError"]>; };
  "HealthData": { "status": string; };
  "HealthResponse": { "data": Schemas["HealthData"]; "meta": Schemas["Meta"]; };
  "ImportConfirm": { "allow_rejected_rows"?: boolean; "confirmed_supersession"?: boolean; "expected_version": number; };
  "ImportData": { "accepted_rows": number; "adapter_version": string; "columns": Array<string>; "created_at": string; "derived_from_import_id": string | null; "duplicate_rows": number; "errors": Array<Schemas["ErrorDetail"]>; "file_sha256": string; "generated_at": string | null; "id": string; "job_id": string; "kind": "PURCHASE" | "PORTAL_2B"; "mapping": Record<string, string>; "period": string; "provenance": "USER_PROVIDED" | "SYNTHETIC_DEMO"; "registration_id": string; "rejected_rows": number; "sheet_name": string | null; "state": "RECEIVED" | "PARSING" | "AWAITING_CONFIRMATION" | "READY" | "FAILED" | "SUPERSEDED"; "supersedes_import_id": string | null; "updated_at": string; "version": number; "workspace_id": string; };
  "ImportListData": { "imports": Array<Schemas["ImportData"]>; "next_cursor": string | null; };
  "ImportListResponse": { "data": Schemas["ImportListData"]; "meta": Schemas["Meta"]; };
  "ImportResponse": { "data": Schemas["ImportData"]; "meta": Schemas["Meta"]; };
  "JobData": { "artifact_id"?: string | null; "created_at": string; "error_code": string | null; "id": string; "import_id"?: string | null; "kind": "IMPORT" | "RUN" | "ARTIFACT"; "run_id"?: string | null; "state": "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED"; "updated_at": string; "workspace_id": string; };
  "JobResponse": { "data": Schemas["JobData"]; "meta": Schemas["Meta"]; };
  "LoginRequest": { "password": string; "username": string; };
  "LogoutData": { "logged_out"?: true; };
  "LogoutResponse": { "data": Schemas["LogoutData"]; "meta": Schemas["Meta"]; };
  "MappingPatch": { "expected_version": number; "mapping": Record<string, string>; "sheet_name"?: string | null; };
  "Meta": { "request_id": string; };
  "PreviewData": { "next_cursor": number | null; "rows": Array<Schemas["PreviewRow"]>; };
  "PreviewResponse": { "data": Schemas["PreviewData"]; "meta": Schemas["Meta"]; };
  "PreviewRow": { "accepted": boolean; "canonical": Record<string, unknown>; "duplicate": boolean; "errors": Array<Schemas["ErrorDetail"]>; "original": Record<string, string | number | number | null>; "row_number": number; };
  "ProposalCreate": { "allocations": Array<Schemas["Allocation"]>; "balance_observations": Array<Schemas["BalanceObservation"]>; "expected_result_versions": Record<string, number>; "expected_run_version": number; "run_id": string; };
  "ProposalData": { "created_at": number; "id": string; "run_id": string; "snapshot": Record<string, unknown>; "snapshot_sha256": string; "sources_current": boolean; "state": "DRAFT" | "APPROVED" | "EXPORTED" | "STALE"; "stored_state": "DRAFT" | "APPROVED" | "EXPORTED"; "timeline": Array<Record<string, unknown>>; "updated_at": number; "version": number; "workspace_id": string; };
  "ProposalListData": { "next_cursor": string | null; "proposals": Array<Schemas["ProposalData"]>; };
  "ProposalListResponse": { "data": Schemas["ProposalListData"]; "meta": Schemas["Meta"]; };
  "ProposalResponse": { "data": Schemas["ProposalData"]; "meta": Schemas["Meta"]; };
  "Reason": { "expected_version": number; "reason": string; };
  "RegistrationData": { "created_at": string; "display_name": string; "gstin": string; "id": string; "version": number; "workspace_id": string; };
  "RegistrationResponse": { "data": Array<Schemas["RegistrationData"]>; "meta": Schemas["Meta"]; };
  "ResultData": { "assigned_portal_document_id": string | null; "canonical": Record<string, string | Array<string> | null>; "id": string; "provenance": "USER_PROVIDED" | "SYNTHETIC_DEMO"; "purchase_document_id": string; "reason_codes": Array<string>; "run_id": string; "source_row_number": number; "status": "EXACT_MATCH" | "FUZZY_SUGGESTION" | "AMOUNT_MISMATCH" | "MISSING_IN_SNAPSHOT" | "AMBIGUOUS" | "EVIDENCE_INCOMPLETE" | "REVIEW_ACCEPTED" | "REJECTED"; "version": number; "workspace_id": string; };
  "ResultDetail": { "assigned_portal_document_id": string | null; "candidates": Array<Schemas["CandidateData"]>; "canonical": Record<string, string | Array<string> | null>; "id": string; "provenance": "USER_PROVIDED" | "SYNTHETIC_DEMO"; "purchase_document_id": string; "reason_codes": Array<string>; "review_timeline": Array<Schemas["ReviewEvent"]>; "run_id": string; "source_row_number": number; "status": "EXACT_MATCH" | "FUZZY_SUGGESTION" | "AMOUNT_MISMATCH" | "MISSING_IN_SNAPSHOT" | "AMBIGUOUS" | "EVIDENCE_INCOMPLETE" | "REVIEW_ACCEPTED" | "REJECTED"; "version": number; "workspace_id": string; };
  "ResultListData": { "next_cursor": number | null; "results": Array<Schemas["ResultData"]>; };
  "ResultListResponse": { "data": Schemas["ResultListData"]; "meta": Schemas["Meta"]; };
  "ResultResponse": { "data": Schemas["ResultDetail"]; "meta": Schemas["Meta"]; };
  "ReviewCreate": { "action": "ACCEPT_CANDIDATE" | "REJECT_MATCH"; "candidate_id"?: string | null; "expected_version": number; "reason": string; };
  "ReviewEvent": { "action": "ACCEPT_CANDIDATE" | "REJECT_MATCH"; "actor_id": string; "candidate_id": string | null; "created_at": string; "reason": string; "result_version": number; };
  "RunCreate": { "period": string; "portal_import_id": string; "purchase_import_id": string; "registration_id": string; };
  "RunData": { "created_at": string; "id": string; "job_id": string; "period": string; "policy": Schemas["RunPolicy"]; "policy_version": string; "portal_import_id": string; "provenance": "USER_PROVIDED" | "SYNTHETIC_DEMO"; "purchase_import_id": string; "registration_id": string; "revision": number; "run_id": string; "sources": Array<Schemas["RunSource"]>; "sources_current": boolean; "state": "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "SUPERSEDED"; "summary": Schemas["RunSummary"] | null; "superseded_by_run_id": string | null; "updated_at": string; "version": number; "workspace_id": string; };
  "RunListData": { "next_cursor": string | null; "runs": Array<Schemas["RunData"]>; };
  "RunListResponse": { "data": Schemas["RunListData"]; "meta": Schemas["Meta"]; };
  "RunPolicy": { "amount_tolerance": string; "comparison": string; "fuzzy_gap": string; "fuzzy_threshold": string; "max_candidates": number; "max_pairs": number; "max_result_bytes": number; "max_rows": number; "version": string; };
  "RunResponse": { "data": Schemas["RunData"]; "meta": Schemas["Meta"]; };
  "RunSource": { "accepted_rows": number; "adapter_version": string; "generated_at": string | null; "id": string; "kind": "PURCHASE" | "PORTAL_2B"; "provenance": "USER_PROVIDED" | "SYNTHETIC_DEMO"; "rejected_rows": number; "sha256": string; "version": number; };
  "RunSummary": { "accepted_purchase_rows": number; "counts": Record<string, number>; "credit_note_tax_review": string; "currency": "INR"; "tax_exposure_review": string; "unknown_credit_note_tax_rows": number; "unknown_tax_exposure_rows": number; };
  "SessionData": { "csrf_token": string; "expires_at": string; "user_id": string; "username": string; };
  "SessionResponse": { "data": Schemas["SessionData"]; "meta": Schemas["Meta"]; };
  "ValidationError": { "ctx"?: Record<string, unknown>; "input"?: unknown; "loc": Array<string | number>; "msg": string; "type": string; };
  "WorksheetResponse": { "data": Record<string, unknown>; "meta": Schemas["Meta"]; };
  "WorkspaceData": { "created_at": string; "id": string; "name": string; "role": "OWNER" | "REVIEWER" | "VIEWER"; "version": number; };
  "WorkspaceResponse": { "data": Array<Schemas["WorkspaceData"]>; "meta": Schemas["Meta"]; };
}
